
CREATE TABLE CAR_INFORM
(
  COMPANY_ID     VARCHAR(50) NOT NULL COMMENT 'COMPANY_ID',
  CAR_NAME_ID    VARCHAR(50) NOT NULL COMMENT '자동차 이름_ID',
  YEAR_ID        VARCHAR(50) NOT NULL COMMENT '연식_ID',
  CAR_OPTIONS_ID VARCHAR(50) NOT NULL COMMENT '자동차 옵션_ID'
) COMMENT '자동차 정보';

CREATE TABLE CAR_NAME
(
  NAME        VARCHAR(50) NOT NULL COMMENT '자동차 이름',
  CAR_NAME_ID VARCHAR(50) NOT NULL COMMENT '자동차 이름_ID',
  YEAR_ID     VARCHAR(50) NOT NULL COMMENT '연식_ID',
  PRIMARY KEY (CAR_NAME_ID)
) COMMENT '자동차 이름';

CREATE TABLE CAR_OPTIONS
(
  OPTIONS        VARCHAR(50) NOT NULL COMMENT '자동차 추가옵션',
  CAR_OPTIONS_ID VARCHAR(50) NOT NULL COMMENT '자동차 옵션_ID',
  PRIMARY KEY (CAR_OPTIONS_ID)
) COMMENT '자동차 옵션';

CREATE TABLE CAR_YEARS
(
  YEAR           INTEGER(50) NOT NULL COMMENT '연식',
  YEAR_ID        VARCHAR(50) NOT NULL COMMENT '연식_ID',
  CAR_OPTIONS_ID VARCHAR(50) NOT NULL COMMENT '자동차 옵션_ID',
  PRIMARY KEY (YEAR_ID)
) COMMENT '자동차 연식';

CREATE TABLE COMPANY
(
  COMPANY    VARCHAR(50) NOT NULL COMMENT '회사이름',
  COMPANY_ID VARCHAR(50) NOT NULL COMMENT 'COMPANY_ID',
  PRIMARY KEY (COMPANY_ID)
) COMMENT '회사 이름';

ALTER TABLE CAR_INFORM
  ADD CONSTRAINT FK_CAR_NAME_TO_CAR_INFORM
    FOREIGN KEY (CAR_NAME_ID)
    REFERENCES CAR_NAME (CAR_NAME_ID);

ALTER TABLE CAR_INFORM
  ADD CONSTRAINT FK_COMPANY_TO_CAR_INFORM
    FOREIGN KEY (COMPANY_ID)
    REFERENCES COMPANY (COMPANY_ID);

ALTER TABLE CAR_YEARS
  ADD CONSTRAINT FK_CAR_OPTIONS_TO_CAR_YEARS
    FOREIGN KEY (CAR_OPTIONS_ID)
    REFERENCES CAR_OPTIONS (CAR_OPTIONS_ID);

ALTER TABLE CAR_NAME
  ADD CONSTRAINT FK_CAR_YEARS_TO_CAR_NAME
    FOREIGN KEY (YEAR_ID)
    REFERENCES CAR_YEARS (YEAR_ID);

ALTER TABLE CAR_INFORM
  ADD CONSTRAINT FK_CAR_YEARS_TO_CAR_INFORM
    FOREIGN KEY (YEAR_ID)
    REFERENCES CAR_YEARS (YEAR_ID);

ALTER TABLE CAR_INFORM
  ADD CONSTRAINT FK_CAR_OPTIONS_TO_CAR_INFORM
    FOREIGN KEY (CAR_OPTIONS_ID)
    REFERENCES CAR_OPTIONS (CAR_OPTIONS_ID);
