
CREATE TABLE ADDRESS
(
  ADDRESS    VARCHAR(500) NOT NULL COMMENT '주소',
  ADDRESS_ID VARCHAR(50)  NOT NULL COMMENT '주소코드_ID',
  PRIMARY KEY (ADDRESS_ID)
) COMMENT '주소';

CREATE TABLE GENDER
(
  GENDER    VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_ID VARCHAR(50) NOT NULL COMMENT '성별코드_ID',
  PRIMARY KEY (GENDER_ID)
) COMMENT '성별';

CREATE TABLE HOBBY_TYPE
(
  HOBBY         VARCHAR(50) NOT NULL COMMENT '취미명',
  HOBBY_TYPE_ID VARCHAR(50) NOT NULL COMMENT '취미코드_ID',
  PRIMARY KEY (HOBBY_TYPE_ID)
) COMMENT '취미 코드';

CREATE TABLE LOGIN
(
  EMAIL     VARCHAR(50) NOT NULL COMMENT '이메일',
  UNIQUE_ID VARCHAR(50) NOT NULL COMMENT 'UNIQUE_ID',
  LOGIN_ID  VARCHAR(50) NOT NULL COMMENT '회원_로그인ID',
  PRIMARY KEY (LOGIN_ID)
) COMMENT '회원_로그인';

CREATE TABLE MEM_HOBBY
(
  UNIQUE_ID     VARCHAR(50) NOT NULL COMMENT 'UNIQUE_ID',
  HOBBY_TYPE_ID VARCHAR(50) NOT NULL COMMENT '취미코드_ID'
) COMMENT '회원_취미';

CREATE TABLE MEM_INFORM
(
  NAME       VARCHAR(50) NOT NULL COMMENT '이름',
  AGE        INTEGER     NOT NULL COMMENT '나이',
  PHONE      VARCHAR(50) NOT NULL COMMENT '전화번호',
  UNIQUE_ID  VARCHAR(50) NOT NULL COMMENT 'UNIQUE_ID',
  GENDER_ID  VARCHAR(50) NOT NULL COMMENT '성별코드_ID',
  ADDRESS_ID VARCHAR(50) NOT NULL COMMENT '주소코드_ID',
  PRIMARY KEY (UNIQUE_ID)
) COMMENT '회원정보';

ALTER TABLE MEM_HOBBY
  ADD CONSTRAINT FK_MEM_INFORM_TO_MEM_HOBBY
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES MEM_INFORM (UNIQUE_ID);

ALTER TABLE LOGIN
  ADD CONSTRAINT FK_MEM_INFORM_TO_LOGIN
    FOREIGN KEY (UNIQUE_ID)
    REFERENCES MEM_INFORM (UNIQUE_ID);

ALTER TABLE MEM_HOBBY
  ADD CONSTRAINT FK_HOBBY_TYPE_TO_MEM_HOBBY
    FOREIGN KEY (HOBBY_TYPE_ID)
    REFERENCES HOBBY_TYPE (HOBBY_TYPE_ID);

ALTER TABLE MEM_INFORM
  ADD CONSTRAINT FK_GENDER_TO_MEM_INFORM
    FOREIGN KEY (GENDER_ID)
    REFERENCES GENDER (GENDER_ID);

ALTER TABLE MEM_INFORM
  ADD CONSTRAINT FK_ADDRESS_TO_MEM_INFORM
    FOREIGN KEY (ADDRESS_ID)
    REFERENCES ADDRESS (ADDRESS_ID);
