
CREATE TABLE ADVICES
(
  ADVICE_LS    VARCHAR(50) NOT NULL COMMENT '유지 방안 항목',
  ADVICE_LS_ID VARCHAR(50) NOT NULL COMMENT '유지 방안 항목_ID',
  PRIMARY KEY (ADVICE_LS_ID)
) COMMENT '유지 방안';

CREATE TABLE EXAM_LIST
(
  EXLIST    VARCHAR(50) NOT NULL COMMENT '재검진 항목',
  EXLIST_ID VARCHAR(50) NOT NULL COMMENT '재검진 항목_ID',
  PRIMARY KEY (EXLIST_ID)
) COMMENT '재검진 항목';

CREATE TABLE GENDER
(
  GENDER    VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_ID VARCHAR(50) NOT NULL COMMENT '성별_ID',
  PRIMARY KEY (GENDER_ID)
) COMMENT '성별';

CREATE TABLE PATIENTS
(
  PATIENT    VARCHAR(50) NOT NULL COMMENT '환자이름',
  HIEGHT     INTEGER     NOT NULL COMMENT '키',
  WEIGHT     INTEGER     NOT NULL COMMENT '체중',
  PRESSURE   VARCHAR(50) NOT NULL COMMENT '혈압',
  BLOODSUGAR INTEGER     NOT NULL COMMENT '당뇨',
  GENDER_ID  VARCHAR(50) NOT NULL COMMENT '성별_ID',
  PATIENT_ID VARCHAR(50) NOT NULL COMMENT '환자_ID',
  PRIMARY KEY (PATIENT_ID)
) COMMENT '환자 정보';

CREATE TABLE PATIENTS_RE_EXAM
(
  RE_EXAM    VARCHAR(50) NOT NULL COMMENT '환자 재검진',
  EXLIST_ID  VARCHAR(50) NOT NULL COMMENT '재검진 항목_ID',
  RE_EXAM_ID VARCHAR(50) NOT NULL COMMENT '환자 재검진_ID',
  PRIMARY KEY (RE_EXAM_ID)
) COMMENT '환자 재검진..이 TABLE은 필요 없을지도. ';

CREATE TABLE RESULTS
(
  PATIENT_ID   VARCHAR(50) NOT NULL COMMENT '환자_ID',
  RESULTS      VARCHAR(50) NOT NULL COMMENT '결과',
  RESULTS_ID   VARCHAR(50) NOT NULL COMMENT '결과_ID',
  RE_EXAM_ID   VARCHAR(50) NOT NULL COMMENT '환자 재검진_ID',
  ADVICE_LS_ID VARCHAR(50) NOT NULL COMMENT '유지 방안 항목_ID',
  PRIMARY KEY (RESULTS_ID)
) COMMENT '환자 결과';

ALTER TABLE RESULTS
  ADD CONSTRAINT FK_ADVICES_TO_RESULTS
    FOREIGN KEY (ADVICE_LS_ID)
    REFERENCES ADVICES (ADVICE_LS_ID);

ALTER TABLE PATIENTS_RE_EXAM
  ADD CONSTRAINT FK_EXAM_LIST_TO_PATIENTS_RE_EXAM
    FOREIGN KEY (EXLIST_ID)
    REFERENCES EXAM_LIST (EXLIST_ID);

ALTER TABLE RESULTS
  ADD CONSTRAINT FK_PATIENTS_RE_EXAM_TO_RESULTS
    FOREIGN KEY (RE_EXAM_ID)
    REFERENCES PATIENTS_RE_EXAM (RE_EXAM_ID);

ALTER TABLE RESULTS
  ADD CONSTRAINT FK_PATIENTS_TO_RESULTS
    FOREIGN KEY (PATIENT_ID)
    REFERENCES PATIENTS (PATIENT_ID);

ALTER TABLE PATIENTS
  ADD CONSTRAINT FK_GENDER_TO_PATIENTS
    FOREIGN KEY (GENDER_ID)
    REFERENCES GENDER (GENDER_ID);
