-- SELECT MIN(column_name)
-- FROM table_name
-- WHERE condition;

-- 성별 당 COUNT는 각각 몇명인가?
SELECT COUNT(*)
FROM MEMBERS
GROUP BY GENDER_CODE_ID; -- <COLUMN의 공통된 값들이 묶인것. 

-- GROUP BY도 ORDER BY처럼 COLUMN여러개 동일 조건으로 묶을 수 잇음
-- ORDER BY <GENDER_CODE_ID, AGE> 
SELECT COUNT(*), GENDER_CODE_ID, MIN(NAME)
FROM MEMBERS
GROUP BY GENDER_CODE_ID;



-- COUNT()를 사용할 때는 * 보다 PRIMARY KEY COLUMN을 넣는 것이 좋다

SELECT COUNT(MEMBERS_ID)
FROM MEMBERS
WHERE GENDER_CODE_ID = 'G-04'
GROUP BY MEMBERS_ID;
