-- SELECT column_name(s)
-- FROM table_name
-- WHERE condition
-- GROUP BY column_name(s)
-- HAVING condition <<WHERE절에 GROUP BY를 묶은 것이 HAVING임
-- ORDER BY column_name(s);

SELECT *
FROM (SELECT COUNT(T_MEMB.AGE) AS CNT_AGE, T_MEMB.AGE
	FROM MEMBERS AS T_MEMB
	GROUP BY T_MEMB.AGE) AS T_INNER_MEMB 
WHERE T_INNER_MEMB.CNT_AGE >=2 ; 





SELECT COUNT(T_MEMB.AGE) AS CNT_AGE, T_MEMB.AGE
FROM MEMBERS AS T_MEMB
GROUP BY T_MEMB.AGE
HAVING COUNT(T_MEMB.AGE) >=2;


SELECT COUNT(T_MEMB.AGE) AS CNT_AGE, T_MEMB.AGE
FROM MEMBERS AS T_MEMB
GROUP BY T_MEMB.AGE;

-- w3school 예제 실습
-- SELECT COUNT(ProductID), AVG(Price), SUM(Price), Price, MIN(Price), MAX(Price)
-- SELECT COUNT(ProductID) AS CNT_ProdID, CategoryID, MIN(Price), Price
-- FROM Products
-- GROUP BY CategoryID; 
